/**
 * pptx.js — 纯前端 .pptx 渲染器（pptxgenjs）+ HTML 预览生成。
 *
 * 职责边界：
 *   - 本文件只负责"结构化 JSON → 可消费产物"；
 *   - 颜色/字体/版式写死在 renderer 里，不让 LLM 碰；
 *   - HTML 预览只用于即时预览，不是交付物。
 */

import PptxGenJS from 'pptxgenjs'

/* ========== 主题 ========== */
const THEME = {
  bg: 'FFFFFF',
  primary: '6366f1', // 紫色主色
  accent: 'f472b6', // 粉色点缀
  text: '1e293b',
  soft: '94a3b8',
  surface: 'F8F7FC',
}

/* ========== 文件生成 ========== */
export async function generatePptxFile(slideData, filename = 'output.pptx') {
  const pptx = new PptxGenJS()
  pptx.layout = 'LAYOUT_16x9'
  pptx.author = 'Rescene Agent'
  pptx.title = slideData.title || 'PPT'

  const slides = Array.isArray(slideData.slides) ? slideData.slides : []

  // 封面
  if (slideData.title) {
    const cover = pptx.addSlide()
    cover.addText(slideData.title, {
      x: 1, y: 2.5, w: 8, h: 1.5,
      fontSize: 32, bold: true, color: THEME.text,
      align: 'center', fontFace: 'PingFang SC',
    })
    cover.addText('Generated by Rescene Agent', {
      x: 1, y: 4.2, w: 8, h: 0.5,
      fontSize: 12, color: THEME.soft, align: 'center',
    })
  }

  // 内容页
  for (const s of slides) {
    const slide = pptx.addSlide()
    slide.addText(s.title || '', {
      x: 0.6, y: 0.45, w: 8.8, h: 0.85,
      fontSize: 24, bold: true, color: THEME.primary,
      fontFace: 'PingFang SC',
    })

    if (Array.isArray(s.bullets) && s.bullets.length) {
      const lines = s.bullets.map(b => ({ text: b, options: { bullet: true, breakLine: true } }))
      slide.addText(lines, {
        x: 0.8, y: 1.35, w: 8.4, h: 4.2,
        fontSize: 18, color: THEME.text,
        lineSpacingMultiple: 1.6, fontFace: 'PingFang SC',
      })
    }

    if (s.notes) {
      slide.addNotes(`备注：${s.notes}`)
    }

    // 底部装饰条（简单色块，不抢内容）
    slide.addShape(pptx.ShapeType.rect, {
      x: 0, y: 6.8, w: 10, h: 0.25,
      fill: { color: THEME.primary },
    })
  }

  await pptx.writeFile({ fileName: filename })
  return filename
}

/* ========== HTML 预览生成（用于预览窗口即时展示） ========== */
export function generatePptxHtml(slideData) {
  const title = escapeHtml(slideData.title || 'PPT 预览')
  const slides = Array.isArray(slideData.slides) ? slideData.slides : []

  const body = slides
    .map(
      (s) => `
    <div class="slide">
      <div class="slide-header">
        <span class="slide-index">${slides.indexOf(s) + 1}</span>
        <div class="slide-title">${escapeHtml(s.title || '')}</div>
      </div>
      <ul class="slide-bullets">
        ${(s.bullets || [])
          .map(
            (b) => `
          <li><span class="bullet-dot"></span><span>${escapeHtml(b)}</span></li>`,
          )
          .join('')}
      </ul>
      ${s.notes ? `<div class="slide-notes">备注：${escapeHtml(s.notes)}</div>` : ''}
      <div class="slide-footer-bar"></div>
    </div>`,
    )
    .join('\n')

  return `<!DOCTYPE html>
<html lang="zh-CN">
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <title>${title}</title>
  <style>
    * { margin: 0; padding: 0; box-sizing: border-box; }
    html, body {
      width: 100%; height: 100%; overflow: hidden;
      font-family: -apple-system, "PingFang SC", "Microsoft YaHei", sans-serif;
      background: ${THEME.surface};
      color: ${THEME.text};
    }
    .stage {
      position: relative; width: 100vw; height: 100vh;
    }
    .slide {
      display: none;
      width: 100%; height: 100%;
      padding: 60px 80px;
      flex-direction: column;
    }
    .slide.active { display: flex; }
    .slide-header { display: flex; align-items: baseline; gap: 16px; margin-bottom: 28px; }
    .slide-index {
      display: inline-flex; align-items: center; justify-content: center;
      width: 36px; height: 36px; border-radius: 10px;
      background: ${THEME.primary}; color: #fff;
      font-size: 14px; font-weight: 700;
    }
    .slide-title {
      font-size: 32px; font-weight: 700; color: ${THEME.primary};
      letter-spacing: -0.3px;
    }
    .slide-bullets { list-style: none; }
    .slide-bullets li {
      display: flex; align-items: flex-start; gap: 12px;
      font-size: 20px; line-height: 1.6; padding: 9px 0;
    }
    .bullet-dot {
      flex-shrink: 0; width: 8px; height: 8px; border-radius: 50%;
      background: ${THEME.accent}; margin-top: 11px;
    }
    .slide-notes {
      margin-top: auto; padding-top: 14px; font-size: 14px; color: ${THEME.soft};
      border-top: 1px solid #e5e5e5;
    }
    .slide-footer-bar {
      position: absolute; left: 0; bottom: 0;
      width: 100%; height: 6px; background: ${THEME.primary};
    }
    .nav {
      position: fixed; right: 20px; bottom: 18px;
      display: flex; gap: 8px; align-items: center;
      background: rgba(255,255,255,0.85); backdrop-filter: blur(8px);
      padding: 8px 12px; border-radius: 999px; border: 1px solid #e5e5e5;
      font-size: 13px; color: ${THEME.text}; box-shadow: 0 4px 12px rgba(0,0,0,0.06);
    }
    .nav button {
      width: 32px; height: 32px; border-radius: 50%; border: 1px solid #e5e5e5;
      background: #fff; cursor: pointer; font-size: 16px; color: ${THEME.text};
    }
    .nav button:hover { background: #f3f3f5; }
  </style>
</head>
<body>
  <div class="stage" id="stage">
    ${body || '<div class="slide active"><div class="slide-title">空内容</div></div>'}
  </div>
  <div class="nav">
    <button id="prev">‹</button>
    <span id="counter">1 / ${slides.length || 1}</span>
    <button id="next">›</button>
  </div>
  <script>
    const stage = document.getElementById('stage');
    const slides = stage.querySelectorAll('.slide');
    const counter = document.getElementById('counter');
    let cur = 0;
    function show(i) {
      cur = ((i % slides.length) + slides.length) % slides.length;
      slides.forEach((s, idx) => s.classList.toggle('active', idx === cur));
      counter.textContent = (cur + 1) + ' / ' + slides.length;
    }
    document.getElementById('prev').onclick = () => show(cur - 1);
    document.getElementById('next').onclick = () => show(cur + 1);
    document.addEventListener('keydown', (e) => {
      if (e.key === 'ArrowLeft') show(cur - 1);
      if (e.key === 'ArrowRight') show(cur + 1);
    });
    show(0);
  <\/script>
</body>
</html>`
}

function escapeHtml(str) {
  return String(str || '')
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#039;')
    .replace(/\n/g, '<br/>')
}
