use skills_bank::components::native_pipeline::*;
use std::fs;
use tempfile::tempdir;

#[tokio::test]
async fn test_native_aggregate_generates_outputs() -> Result<(), Box<dyn std::error::Error>> {
    let root = tempdir()?;
    let src = root.path().join("src").join("demo-repo").join("skills").join("sample-skill");
    fs::create_dir_all(&src)?;

    let skill_md = r#"---
name: sample-skill
description: sample skill for testing
---

body
"#;
    fs::write(src.join("SKILL.md"), skill_md)?;

    let output = root.path().join("skills-aggregated");
    let skills = aggregate_to_output(root.path(), &output, None, true, false).await?;

    assert_eq!(skills.len(), 1);
    assert!(output.join("subhub-index.json").exists());

    // Debug: list output directory contents to help diagnose test failures.
    fn print_dir(path: &std::path::Path) {
        if let Ok(entries) = std::fs::read_dir(path) {
            for entry in entries.flatten() {
                let p = entry.path();
                println!("OUT: {}", p.display());
                if p.is_dir() {
                    if let Ok(sub) = std::fs::read_dir(&p) {
                        for s in sub.flatten() {
                            println!("  SUB: {}", s.path().display());
                        }
                    }
                }
            }
        }
    }

    print_dir(&output);

    // subhub manifest should be present for the subhub (use returned skill's hub/sub_hub)
    let hub = &skills[0].hub;
    let sub_hub = &skills[0].sub_hub;
    assert!(output.join(hub).join(sub_hub).join("skills-manifest.json").exists());
    // SKILL.md is no longer generated by the native pipeline
    assert!(!output.join("SKILL.md").exists());

    Ok(())
}

#[test]
fn test_sync_output_copy_mode() -> Result<(), Box<dyn std::error::Error>> {
    let root = tempdir()?;
    let source = root.path().join("skills-aggregated");
    let target = root.path().join("target").join("skills");

    fs::create_dir_all(source.join("server-side").join("agents"))?;
    fs::write(
        source.join("server-side").join("agents").join("routing.csv"),
        "skill_id,triggers,score,src_path\n",
    )?;

    sync_output_to_targets(&source, &[target.clone()], NativeSyncMode::Copy)?;
    assert!(target.join("server-side").join("agents").join("routing.csv").exists());

    Ok(())
}

#[test]
fn test_sync_cleanup_removes_stale_link_temp_sibling() -> Result<(), Box<dyn std::error::Error>> {
    let root = tempdir()?;
    let source = root.path().join("skills-aggregated");
    let target = root.path().join(".github").join("skills");
    let stale_tmp = root.path().join(".github").join("skills.link.tmp");

    fs::create_dir_all(source.join("server-side").join("agents"))?;
    fs::write(
        source.join("server-side").join("agents").join("routing.csv"),
        "skill_id,triggers,score,src_path\n",
    )?;

    fs::create_dir_all(&target)?;
    fs::create_dir_all(&stale_tmp)?;
    fs::write(stale_tmp.join("leftover.txt"), "stale")?;

    sync_output_to_targets(&source, &[target.clone()], NativeSyncMode::Copy)?;

    assert!(target.join("server-side").join("agents").join("routing.csv").exists());
    assert!(!stale_tmp.exists(), "stale .link.tmp sibling should be removed");

    Ok(())
}
