/**
 * @module GitIntegration
 *
 * Git 集成与版本回滚管理器。
 *
 * 核心能力：
 * 1. 任务执行前自动创建 Git 分支
 * 2. 合并后自动 commit
 * 3. 质检失败时自动回滚
 * 4. 支持 diff 审查
 * 5. 操作历史追踪
 */

const { spawnSync } = require('child_process');
const fs = require('fs');
const path = require('path');
const logger = require('../utils/Logger')('GitIntegration');

class GitIntegration {
  constructor (options = {}) {
    this.workspaceDir = options.workspaceDir || process.cwd();
    this.autoCommit = options.autoCommit !== false;
    this.autoBranch = options.autoBranch !== false;
    this.branchPrefix = options.branchPrefix || 'qidi/';
    this._enabled = null;
  }

  /**
   * 检查 Git 是否可用
   */
  isEnabled () {
    if (this._enabled !== null) return this._enabled;
    try {
      const result = spawnSync('git', ['rev-parse', '--is-inside-work-tree'], {
        cwd: this.workspaceDir, encoding: 'utf-8', timeout: 5000
      });
      this._enabled = result.status === 0 && result.stdout.trim() === 'true';
    } catch (_) {
      this._enabled = false;
    }
    return this._enabled;
  }

  _git (args, options = {}) {
    const result = spawnSync('git', args, {
      cwd: options.cwd || this.workspaceDir,
      encoding: 'utf-8',
      timeout: options.timeout || 30000
    });
    return {
      success: result.status === 0,
      stdout: result.stdout?.trim() || '',
      stderr: result.stderr?.trim() || '',
      code: result.status
    };
  }

  /**
   * 初始化 Git 仓库（如果不存在）
   */
  initRepo () {
    if (!this.isEnabled()) {
      logger.info('[GitIntegration] 初始化 Git 仓库');
      this._git(['init']);
      this._git(['config', 'user.email', 'qidi-agent@local']);
      this._git(['config', 'user.name', 'Qidi Agent']);
      this._git(['add', '-A']);
      this._git(['commit', '-m', 'Qidi Agent: 初始提交']);
      this._enabled = true;
    }
    return this.isEnabled();
  }

  /**
   * 任务执行前：创建分支
   */
  createTaskBranch (taskId) {
    if (!this.isEnabled()) return null;
    const branchName = `${this.branchPrefix}${taskId}`;
    const result = this._git(['checkout', '-b', branchName]);
    if (result.success) {
      logger.info(`[GitIntegration] 创建分支: ${branchName}`);
      return branchName;
    }
    // 可能分支已存在
    const switchResult = this._git(['checkout', branchName]);
    return switchResult.success ? branchName : null;
  }

  /**
   * 合并后：自动提交
   */
  commitChanges (taskId, message = '') {
    if (!this.isEnabled() || !this.autoCommit) return null;

    this._git(['add', '-A']);

    const commitMessage = message || `Qidi Agent: 任务 ${taskId} 完成\n\nGenerated by Qidi Agent on ${new Date().toISOString()}`;
    const result = this._git(['commit', '-m', commitMessage, '--allow-empty']);

    if (result.success) {
      const hash = this._git(['rev-parse', 'HEAD']).stdout;
      logger.info(`[GitIntegration] 提交: ${hash.substring(0, 8)}`);
      return hash;
    }
    return null;
  }

  /**
   * 质检失败：回滚到指定 commit
   */
  rollback (commitHash = null) {
    if (!this.isEnabled()) return false;

    if (commitHash) {
      // 回滚到指定 commit
      const result = this._git(['reset', '--hard', commitHash]);
      logger.info(`[GitIntegration] 回滚到: ${commitHash.substring(0, 8)}`);
      return result.success;
    } else {
      // 回滚所有未提交的变更
      this._git(['checkout', '--', '.']);
      this._git(['clean', '-fd']);
      logger.info('[GitIntegration] 回滚所有未提交变更');
      return true;
    }
  }

  /**
   * 合并分支回主分支
   */
  mergeToMain (branchName) {
    if (!this.isEnabled()) return false;

    const currentBranch = this._git(['rev-parse', '--abbrev-ref', 'HEAD']).stdout;
    this._git(['checkout', 'main']);
    const result = this._git(['merge', branchName, '--no-ff', '-m', `Qidi Agent: 合并 ${branchName}`]);

    if (result.success) {
      logger.info(`[GitIntegration] 合并 ${branchName} -> main`);
      // 删除分支
      this._git(['branch', '-d', branchName]);
    }

    // 切回原分支
    if (currentBranch && currentBranch !== 'main') {
      this._git(['checkout', currentBranch]);
    }

    return result.success;
  }

  /**
   * 获取 diff
   */
  getDiff (commitHash = null) {
    if (!this.isEnabled()) return '';

    if (commitHash) {
      return this._git(['diff', commitHash, 'HEAD']).stdout;
    }
    return this._git(['diff']).stdout;
  }

  /**
   * 获取文件变更列表
   */
  getChangedFiles (commitHash = null) {
    if (!this.isEnabled()) return [];

    const args = commitHash
      ? ['diff', '--name-status', commitHash, 'HEAD']
      : ['status', '--porcelain'];

    const result = this._git(args);
    if (!result.stdout) return [];

    return result.stdout.split('\n').filter(l => l.trim()).map(line => {
      const parts = line.split('\t');
      return {
        status: parts[0]?.trim() || 'M',
        path: parts[1]?.trim() || line.trim()
      };
    });
  }

  /**
   * 获取提交历史
   */
  getLog (limit = 20) {
    if (!this.isEnabled()) return [];

    const result = this._git(['log', `--max-count=${limit}`, '--pretty=format:%H|%an|%ad|%s', '--date=short']);
    if (!result.stdout) return [];

    return result.stdout.split('\n').map(line => {
      const [hash, author, date, ...msgParts] = line.split('|');
      return { hash, author, date, message: msgParts.join('|') };
    });
  }

  /**
   * 获取当前分支名
   */
  getCurrentBranch () {
    if (!this.isEnabled()) return null;
    return this._git(['rev-parse', '--abbrev-ref', 'HEAD']).stdout;
  }

  /**
   * 为任务创建保存点
   */
  createSavepoint (taskId) {
    if (!this.isEnabled()) return null;
    const hash = this.commitChanges(taskId, `Qidi Agent: 保存点 ${taskId}`);
    return hash;
  }

  /**
   * 恢复到保存点
   */
  restoreSavepoint (commitHash) {
    return this.rollback(commitHash);
  }
}

module.exports = GitIntegration;
