pip install -e .
Usage

bash
复制
下载
python main.py
Tools

{tools_list}
'''
}
},
"coze_plugin": {
"description": "Coze插件模板",
"structure": {
"plugin_config": {
"name": "{plugin_name}",
"version": "1.0.0",
"description": "{plugin_description}",
"author": "{author}",
"nodes": [],
"edges": []
}
}
},
"web_api": {
"description": "Web API模板",
"files": {
"app.py": '''from fastapi import FastAPI, HTTPException
from pydantic import BaseModel
import uvicorn

app = FastAPI(title="{api_name}")

class RequestModel(BaseModel):
data: str

class ResponseModel(BaseModel):
success: bool
message: str
result: Any

@app.get("/")
async def root():
return {"message": "{api_name} API"}

@app.post("/process")
async def process_data(request: RequestModel):
try:
result = {"processed": request.data}
return ResponseModel(
success=True,
message="Processing successful",
result=result
)
except Exception as e:
raise HTTPException(status_code=500, detail=str(e))

if name == "main":
uvicorn.run(app, host="0.0.0.0", port=8000)
'''
}
}
}
return default_templates

def generate_code(self, requirements: str, language: str = "python",
template_type: str = "auto_detect") -> Dict[str, Any]:
self.logger.info(f"生成代码: 语言={language}, 模板={template_type}")
if template_type == "auto_detect":
template_type = self._detect_template_type(requirements)
if template_type == "mcp_server":
result = self._generate_mcp_server(requirements)
elif template_type == "coze_plugin":
result = self._generate_coze_plugin(requirements)
elif template_type == "web_api":
result = self._generate_web_api(requirements)
else:
result = self._generate_general_code(requirements, language)
result["validation"] = self._validate_generated_code(result)
return result

def _detect_template_type(self, requirements: str) -> str:
if "mcp" in requirements.lower() and "server" in requirements.lower():
return "mcp_server"
elif "coze" in requirements.lower() and "plugin" in requirements.lower():
return "coze_plugin"
elif "api" in requirements.lower() or "web" in requirements.lower():
return "web_api"
return "general"

def _generate_mcp_server(self, requirements: str) -> Dict[str, Any]:
server_name = "AutoGeneratedMCPServer"
description = "自动生成的MCP服务器"
name_match = re.search(r'名称[:：]\s([^\n]+)', requirements)
if name_match:
server_name = name_match.group(1).strip()
desc_match = re.search(r'描述[:：]\s([^\n]+)', requirements)
if desc_match:
description = desc_match.group(1).strip()
tools_code = """
@server.tool()
async def process_data(data: str) -> Dict[str, Any]:
"""处理数据工具"""
return {"result": f"Processed: {data}", "status": "success"}
"""
return {
"generated_code": self.templates["mcp_server"]["files"]["main.py"].format(
server_name=server_name,
description=description,
tools_code=tools_code,
extra_dependencies="",
tools_list="- process_data: 处理数据工具"
),
"file_structure": {
"main.py": "主程序文件",
"requirements.txt": "依赖文件",
"README.md": "说明文档"
},
"dependencies": ["mcp>=1.0.0"]
}

def _generate_coze_plugin(self, requirements: str) -> Dict[str, Any]:
plugin_name = "AutoGeneratedPlugin"
plugin_description = "自动生成的Coze插件"
author = "Auto Generator"
name_match = re.search(r'插件名称[:：]\s([^\n]+)', requirements)
if name_match:
plugin_name = name_match.group(1).strip()
desc_match = re.search(r'描述[:：]\s([^\n]+)', requirements)
if desc_match:
plugin_description = desc_match.group(1).strip()
author_match = re.search(r'作者[:：]\s*([^\n]+)', requirements)
if author_match:
author = author_match.group(1).strip()
return {
"generated_code": json.dumps({
"plugin_config": {
"name": plugin_name,
"version": "1.0.0",
"description": plugin_description,
"author": author,
"nodes": [
{"id": "node_1", "type": "input", "name": "输入节点"},
{"id": "node_2", "type": "process", "name": "处理节点"},
{"id": "node_3", "type": "output", "name": "输出节点"}
],
"edges": [
{"from": "node_1", "to": "node_2"},
{"from": "node_2", "to": "node_3"}
]
}
}, indent=2, ensure_ascii=False),
"file_structure": {
"plugin_config.json": "插件配置文件"
},
"dependencies": []
}

def _generate_web_api(self, requirements: str) -> Dict[str, Any]:
api_name = "AutoGeneratedAPI"
name_match = re.search(r'API名称[:：]\s*([^\n]+)', requirements)
if name_match:
api_name = name_match.group(1).strip()
return {
"generated_code": self.templates["web_api"]["files"]["app.py"].format(api_name=api_name),
"file_structure": {"app.py": "API主程序"},
"dependencies": ["fastapi", "uvicorn", "pydantic"]
}

def _generate_general_code(self, requirements: str, language: str) -> Dict[str, Any]:
code_templates = {
"python": '''#!/usr/bin/env python3

-- coding: utf-8 --
"""
Auto-generated Python code

Requirements: {requirements}
"""

def main():
print("Auto-generated code based on requirements")
return {"status": "success", "message": "Code generated successfully"}

if name == "main":
main()
''',
"javascript": '''/**

Auto-generated JavaScript code

Requirements: {requirements}
*/

function main() {
console.log("Auto-generated code based on requirements");
return { status: "success", message: "Code generated successfully" };
}

if (require.main === module) {
main();
}
''',
"typescript": '''/**

Auto-generated TypeScript code

Requirements: {requirements}
*/

interface Result {
status: string;
message: string;
}

function main(): Result {
console.log("Auto-generated code based on requirements");
return { status: "success", message: "Code generated successfully" };
}

if (require.main === module) {
main();
}
''',
"java": '''/**

Auto-generated Java code

Requirements: {requirements}
*/

public class AutoGenerated {
public static void main(String[] args) {
System.out.println("Auto-generated code based on requirements");
}
}
''',
"go": '''// Auto-generated Go code
// Requirements: {requirements}

package main

import "fmt"

func main() {
fmt.Println("Auto-generated code based on requirements")
}
''',
"rust": '''// Auto-generated Rust code
// Requirements: {requirements}

fn main() {
println!("Auto-generated code based on requirements");
}
'''
}
template = code_templates.get(language, code_templates["python"])
return {
"generated_code": template.format(requirements=requirements),
"file_structure": {f"main.{self._get_extension(language)}": "主程序文件"},
"dependencies": []
}

def _get_extension(self, language: str) -> str:
ext_map = {
"python": "py",
"javascript": "js",
"typescript": "ts",
"java": "java",
"go": "go",
"rust": "rs"
}
return ext_map.get(language, "txt")

def _validate_generated_code(self, result: Dict[str, Any]) -> Dict[str, Any]:
validation = {
"syntax_ok": True,
"warnings": [],
"errors": []
}
code = result.get("generated_code", "")
if not code:
validation["errors"].append("代码为空")
validation["syntax_ok"] = False
if "main.py" in result.get("file_structure", {}) or "py" in result.get("file_structure", {}):
try:
compile(code, "<string>", "exec")
except SyntaxError as e:
validation["errors"].append(f"Python语法错误: {e}")
validation["syntax_ok"] = False
return validation

===================================================================
批量处理器
===================================================================
class BatchProcessor:
def init(self, config: UnifiedSystemConfig):
self.config = config
self.logger = logging.getLogger(name)

def process_directory(self, directory: str, operation_mode: str = "auto_detect",
automation_level: str = "standard",
max_workers: int = 4,
recursive: bool = True) -> Dict[str, Any]:
start_time = time.time()
self.logger.info(f"开始批量处理: {directory}")
file_patterns = self._get_file_patterns(operation_mode)
files = self._get_files(directory, file_patterns, recursive)
if not files:
return {
"success": True,
"total_files": 0,
"processed_files": 0,
"successful": 0,
"failed": 0,
"processing_time": time.time() - start_time,
"message": "未找到匹配的文件"
}
results = []
with ThreadPoolExecutor(max_workers=max_workers) as executor:
futures = {
executor.submit(self._process_single_file, file_path, operation_mode, automation_level): file_path
for file_path in files
}
for future in as_completed(futures):
file_path = futures[future]
try:
result = future.result()
results.append(result)
except Exception as e:
self.logger.error(f"处理文件失败 {file_path}: {e}")
results.append({
"file": str(file_path),
"success": False,
"error": str(e)
})
successful = sum(1 for r in results if r.get("success", False))
failed = len(results) - successful
return {
"success": True,
"total_files": len(files),
"processed_files": len(results),
"successful": successful,
"failed": failed,
"results": results,
"processing_time": time.time() - start_time,
"export_file": self._generate_report(results, directory)
}

def _get_file_patterns(self, operation_mode: str) -> List[str]:
if operation_mode == "coze_json_repair":
return [".json", ".yaml", ".yml"]
elif operation_mode == "code_generation":
return [".py", ".js", ".ts", ".java"]
elif operation_mode == "data_processing":
return [".json", ".yaml", ".csv", ".xml"]
else:
return [""]

def _get_files(self, directory: str, patterns: List[str], recursive: bool) -> List[Path]:
path = Path(directory)
files = []
for pattern in patterns:
if recursive:
files.extend(path.rglob(pattern))
else:
files.extend(path.glob(pattern))
return files

def _process_single_file(self, file_path: Path, operation_mode: str,
automation_level: str) -> Dict[str, Any]:
try:
with open(file_path, 'r', encoding='utf-8') as f:
content = f.read()
if operation_mode == "coze_json_repair":
processor = JSONProcessor(self.config)
result = processor.repair_json(content)
repaired_content = json.dumps(result, indent=2, ensure_ascii=False)
elif operation_mode == "code_generation":
generator = CodeGenerator(self.config)
result = generator.generate_code(content, "python")
repaired_content = result["generated_code"]
else:
repaired_content = content
output_path = file_path.parent / f"{file_path.stem}_repaired{file_path.suffix}"
with open(output_path, 'w', encoding='utf-8') as f:
f.write(repaired_content)
return {
"file": str(file_path),
"output": str(output_path),
"success": True,
"original_size": len(content),
"final_size": len(repaired_content)
}
except Exception as e:
self.logger.error(f"处理文件失败 {file_path}: {e}")
return {
"file": str(file_path),
"success": False,
"error": str(e)
}

def generate_report(self, results: List[Dict[str, Any]], directory: str) -> str:
report = []
report.append("=" * 80)
report.append("批量处理报告")
report.append("=" * 80)
report.append(f"处理时间: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
report.append(f"目录: {directory}")
report.append("")
successful = [r for r in results if r.get("success", False)]
failed = [r for r in results if not r.get("success", False)]
report.append(f"总文件数: {len(results)}")
report.append(f"成功: {len(successful)}")
report.append(f"失败: {len(failed)}")
report.append("")
if successful:
report.append("成功文件:")
for r in successful:
report.append(f" ✅ {r['file']}")
if failed:
report.append("失败文件:")
for r in failed:
report.append(f" ❌ {r['file']} - {r.get('error', '未知错误')}")
report_path = Path(directory) / f"batch_report{datetime.now().strftime('%Y%m%d_%H%M%S')}.txt"
with open(report_path, 'w', encoding='utf-8') as f:
f.write('\n'.join(report))
return str(report_path)

===================================================================
系统监控器
===================================================================
class SystemMonitor:
def init(self, config: UnifiedSystemConfig):
self.config = config
self.logger = logging.getLogger(name)
self.start_time = time.time()
self.operation_stats = {
"total": 0,
"successful": 0,
"failed": 0
}

def get_system_status(self) -> Dict[str, Any]:
status = {
"status": "healthy",
"timestamp": datetime.now().isoformat(),
"uptime": int(time.time() - self.start_time),
"version": self.config.version,
"operations": {
"total": self.operation_stats["total"],
"successful": self.operation_stats["successful"],
"failed": self.operation_stats["failed"],
"success_rate": self._calculate_success_rate()
},
"components": {
"database": "connected",
"automation_engine": "running",
"code_generator": "running",
"workflow_engine": "running"
},
"resource_usage": self._get_resource_usage()
}
return status

def generate_report(self, report_type: str = "daily") -> Dict[str, Any]:
now = datetime.now()
if report_type == "hourly":
period = now - timedelta(hours=1)
elif report_type == "daily":
period = now - timedelta(days=1)
elif report_type == "weekly":
period = now - timedelta(weeks=1)
elif report_type == "monthly":
period = now - timedelta(days=30)
else:
period = now - timedelta(days=1)
return {
"report_type": report_type,
"time_period": f"{period.strftime('%Y-%m-%d %H:%M:%S')} - {now.strftime('%Y-%m-%d %H:%M:%S')}",
"summary": {
"total_operations": self.operation_stats["total"],
"success_rate": self._calculate_success_rate(),
"uptime": int(time.time() - self.start_time)
},
"recommendations": self._generate_recommendations()
}

def record_operation(self, success: bool):
self.operation_stats["total"] += 1
if success:
self.operation_stats["successful"] += 1
else:
self.operation_stats["failed"] += 1

def _calculate_success_rate(self) -> float:
total = self.operation_stats["total"]
if total == 0:
return 100.0
return (self.operation_stats["successful"] / total) * 100

def _get_resource_usage(self) -> Dict[str, float]:
usage = {"cpu_percent": 0.0, "memory_percent": 0.0, "disk_percent": 0.0}
if psutil:
try:
usage["cpu_percent"] = psutil.cpu_percent(interval=0.1)
usage["memory_percent"] = psutil.virtual_memory().percent
usage["disk_percent"] = psutil.disk_usage('/').percent
except:
pass
return usage

def _generate_recommendations(self) -> List[str]:
recommendations = []
success_rate = self._calculate_success_rate()
if success_rate < 90:
recommendations.append("成功率低于90%，建议检查错误日志")
if self._get_resource_usage().get("memory_percent", 0) > 80:
recommendations.append("内存使用率超过80%，建议增加内存或优化应用")
return recommendations

===================================================================
统一内容处理器
===================================================================
class UnifiedContentProcessor:
def init(self, config: UnifiedSystemConfig):
self.config = config
self.logger = logging.getLogger(name)
self.json_processor = JSONProcessor(config)
self.error_fixer = ErrorFixer(config)
self.code_generator = CodeGenerator(config)
self.batch_processor = BatchProcessor(config)
self.system_monitor = SystemMonitor(config)

def process(self, content: Any, operation_mode: str = "auto_detect",
automation_level: str = "standard") -> Dict[str, Any]:
self.logger.info(f"处理内容: 模式={operation_mode}, 自动化级别={automation_level}")
start_time = time.time()
result = {
"success": True,
"operation": operation_mode,
"automation_level": automation_level,
"timestamp": datetime.now().isoformat()
}
try:
if operation_mode == "auto_detect":
operation_mode = self._detect_operation_mode(content)
if operation_mode == "coze_json_repair":
processed = self._process_json_repair(content, automation_level)
elif operation_mode == "code_generation":
processed = self._process_code_generation(content, automation_level)
elif operation_mode == "workflow_repair":
processed = self._process_workflow_repair(content, automation_level)
else:
processed = self._process_general(content, automation_level)
result.update(processed)
result["processing_time"] = time.time() - start_time
result["success"] = True
except Exception as e:
self.logger.error(f"处理失败: {e}")
result["success"] = False
result["error"] = str(e)
result["processing_time"] = time.time() - start_time
self.system_monitor.record_operation(result["success"])
return result

def _detect_operation_mode(self, content: Any) -> str:
if isinstance(content, str):
if "plugin" in content.lower() and "json" in content.lower():
return "coze_json_repair"
elif "generate" in content.lower() and "code" in content.lower():
return "code_generation"
elif "workflow" in content.lower():
return "workflow_repair"
return "general"

def _process_json_repair(self, content: Any, automation_level: str) -> Dict[str, Any]:
if isinstance(content, str):
result = self.json_processor.repair_json(content, auto_fix=True)
return {
"repaired_content": json.dumps(result, indent=2, ensure_ascii=False),
"validation": self.json_processor.validate_structure(result)
}
return {"error": "内容不是字符串格式"}

def _process_code_generation(self, content: Any, automation_level: str) -> Dict[str, Any]:
if isinstance(content, str):
result = self.code_generator.generate_code(content)
return {
"generated_code": result["generated_code"],
"file_structure": result["file_structure"],
"dependencies": result["dependencies"],
"validation": result.get("validation", {})
}
return {"error": "内容不是字符串格式"}

def _process_workflow_repair(self, content: Any, automation_level: str) -> Dict[str, Any]:
if isinstance(content, dict):
errors = []
if "name" not in content:
errors.append("缺少name字段")
if "version" not in content:
errors.append("缺少version字段")
if errors:
content = self.error_fixer.fix_workflow(content, errors)
return {
"repaired_workflow": content,
"errors_fixed": errors,
"validation": {"valid": True}
}
else:
return {
"workflow": content,
"validation": {"valid": True}
}
return {"error": "内容不是字典格式"}

def _process_general(self, content: Any, automation_level: str) -> Dict[str, Any]:
analysis = self.error_fixer.analyze_errors(content)
if analysis.get("severity") in ["medium", "high"] and automation_level in ["standard", "comprehensive", "full"]:
fixed = self.error_fixer.apply_fixes(content, analysis)
verification = self.error_fixer.verify_fixes(content, fixed, analysis)
return {
"processed": fixed,
"analysis": analysis,
"verification": verification,
"fixes_applied": verification.get("successful", False)
}
else:
return {
"processed": content,
"analysis": analysis,
"fixes_applied": False
}

===================================================================
统一自动化工具主类
===================================================================
class UnifiedAutomationTool:
def init(self, config_file: Optional[str] = None):
if config_file and Path(config_file).exists():
with open(config_file, 'r', encoding='utf-8') as f:
config_dict = yaml.safe_load(f)
self.config = UnifiedSystemConfig(**config_dict)
else:
self.config = UnifiedSystemConfig()
self.processor = UnifiedContentProcessor(self.config)
self.logger = logging.getLogger(name)
self.logger.info("统一自动化工具初始化完成")
self.logger.info(f"版本: {self.config.version}")

def process(self, content: Any, operation_mode: str = "auto_detect",
automation_level: str = "standard") -> Dict[str, Any]:
return self.processor.process(content, operation_mode, automation_level)

def batch_process(self, directory: str, operation_mode: str = "auto_detect",
automation_level: str = "standard",
max_workers: int = 4) -> Dict[str, Any]:
return self.processor.batch_processor.process_directory(
directory, operation_mode, automation_level, max_workers
)

def get_system_status(self) -> Dict[str, Any]:
return self.processor.system_monitor.get_system_status()

def generate_report(self, report_type: str = "daily") -> Dict[str, Any]:
return self.processor.system_monitor.generate_report(report_type)

===================================================================
主程序入口
===================================================================
def main():
parser = argparse.ArgumentParser(
description="统一智能自动化工具套件 - 完全整合版",
formatter_class=argparse.RawDescriptionHelpFormatter,
epilog="""
使用示例:

交互式模式 (推荐)
python unified_automation_tool.py --interactive

处理单个内容
python unified_automation_tool.py --process "内容" --mode coze_json_repair

批量处理目录
python unified_automation_tool.py --batch ./data --mode auto_detect

查看系统状态
python unified_automation_tool.py --status

生成报告
python unified_automation_tool.py --report daily

使用配置文件
python unified_automation_tool.py --config my_config.yaml --interactive
"""
)

parser.add_argument("--config", help="配置文件路径")
parser.add_argument("--interactive", action="store_true", help="启动交互式模式")
parser.add_argument("--process", help="处理单个内容")
parser.add_argument("--mode", help="操作模式", default="auto_detect")
parser.add_argument("--automation", help="自动化级别", default="standard")
parser.add_argument("--output-format", help="输出格式", default="json_pretty")
parser.add_argument("--batch", help="批量处理目录")
parser.add_argument("--max-workers", type=int, help="最大并行数", default=4)
parser.add_argument("--status", action="store_true", help="查看系统状态")
parser.add_argument("--report", help="生成报告 (hourly/daily/weekly)")
parser.add_argument("--cleanup", type=int, help="清理旧数据 (天数)")
parser.add_argument("--save-session", action="store_true", help="保存当前会话")

args = parser.parse_args()

try:
tool = UnifiedAutomationTool(args.config)
except KeyboardInterrupt:
print("\n\n🛑 程序被用户中断")
sys.exit(0)
except Exception as e:
print(f"❌ 程序执行失败: {e}")
logging.exception("程序执行错误")
sys.exit(1)

if args.interactive:
print("\n" + "=" * 80)
print("统一智能自动化工具套件 - 完全整合版")
print("=" * 80)
print(f"版本: {tool.config.version}")
print("\n可用命令:")
print(" process <内容> - 处理内容")
print(" batch <目录> - 批量处理目录")
print(" status - 查看系统状态")
print(" report - 生成报告")
print(" help - 显示帮助")
print(" exit - 退出")

while True:
try:
cmd = input("\n> ").strip()
if not cmd:
continue
parts = cmd.split(maxsplit=1)
if parts[0] == "exit":
print("退出程序")
break
elif parts[0] == "help":
print("可用命令: process, batch, status, report, help, exit")
elif parts[0] == "status":
result = tool.get_system_status()
print(json.dumps(result, indent=2, ensure_ascii=False))
elif parts[0] == "report":
result = tool.generate_report()
print(json.dumps(result, indent=2, ensure_ascii=False))
elif parts[0] == "process":
if len(parts) < 2:
print("❌ 请提供要处理的内容")
continue
content = parts[1]
result = tool.process(content, args.mode, args.automation)
print(json.dumps(result, indent=2, ensure_ascii=False))
elif parts[0] == "batch":
if len(parts) < 2:
print("❌ 请提供要处理的目录")
continue
directory = parts[1]
result = tool.batch_process(directory, args.mode, args.automation, args.max_workers)
print(json.dumps(result, indent=2, ensure_ascii=False))
else:
print(f"❌ 未知命令: {parts[0]}")
except KeyboardInterrupt:
print("\n退出程序")
break
except Exception as e:
print(f"❌ 执行失败: {e}")

elif args.process:
result = tool.process(args.process, args.mode, args.automation)
print(json.dumps(result, indent=2, ensure_ascii=False))

elif args.batch:
result = tool.batch_process(args.batch, args.mode, args.automation, args.max_workers)
print(json.dumps(result, indent=2, ensure_ascii=False))

elif args.status:
result = tool.get_system_status()
print(json.dumps(result, indent=2, ensure_ascii=False))

elif args.report:
result = tool.generate_report(args.report)
print(json.dumps(result, indent=2, ensure_ascii=False))

else:
parser.print_help()

if name == "main":
main()

text
复制
下载

---

## 5. 完整Python修复工具（ultimate_repair_tool.py）